server:
  port: 8085
spring:
  application:
    name: cloud-payment-serviceconslu8004
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        service-name: ${spring.application.name}
        heartbeat:
          enabled: true
name: lisi
